name: 'Fibonacci Calculation and PR Comment'
description: 'Calculate Fibonacci numbers and post results as PR comments'
author: 'Your Name'

inputs:
  enable_fibbot:
    description: 'Enable or disable the Fibonacci bot'
    required: true
    default: 'true'
  max_threshold:
    description: 'Maximum threshold for Fibonacci calculation'
    required: true
    default: '100'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install jq
      run: sudo apt-get install -y jq
  
