name: fibbot input action

description: "An action that takes parameters and inputs"

inputs:
  enable_fib:
    description: "Enable if the fibo calculation should take place or not"
    required: true
    default: "false"
  Max_threshold:
    description: "Set a max value to which the fibo calculation is supposed to stop"
    required: "100"
    default: "100"

runs:
  using: "docker"  # Specify the runtime environment
  image: "Dockerfile"  # Specify the Dockerfile for building the image


