name: 'Fibonacci Bot'
description: 'A custom action to enable or disable the Fibonacci bot and set a maximum threshold.'
inputs:
  enable_fibbot:
    description: 'Enable or disable the Fibonacci bot'
    required: true
    default: 'true'
  max_threshold:
    description: 'Maximum threshold for Fibonacci calculation'
    required: true
    default: "100"
runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "INPUT_ENABLE_FIB=${{ inputs.enable_fibbot }}" >> $GITHUB_ENV
        echo "INPUT_MAX_THRESHOLD=${{ inputs.max_threshold }}" >> $GITHUB_ENV

    - name: Set GITHUB_OWNER
      run: |
       echo "GITHUB_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
    - name: Check if Fibonacci bot is enabled
      shell: bash
      run: |
        if [ "${{ inputs.enable_fibbot }}" == "true" ]; then
          echo "Fibonacci bot is enabled."
        else
          echo "Fibonacci bot is disabled."
        fi

    - name: Validate max threshold
      shell: bash
      run: |
        if [ "${{ inputs.max_threshold }}" -gt 0 ]; then
          echo "Max threshold is valid: ${{ inputs.max_threshold }}"
        else
          echo "Max threshold must be greater than 0."
          exit 1
        fi