name: fibbot input action

description: "An action that takes parameters and inputs"

inputs:
  enable_fibbot:
    description: "Enable if the fibo calculation should take place or not"
    required: true
    default:  "true"
  max_threshold:
    description: "Set a max value to which the fibo calculation is supposed to stop"
    required: true
    default: "100"

runs:
  using: "docker"  # Specify the runtime environment
  image: "Dockerfile"  # Specify the Dockerfile for building the image


 let pr_number: u32 = env::var("GITHUB_REF").ok().and_then(|ref_value| ref_value.split('/').nth(2)?.parse().ok()).context("it is not possible please restart")?;
     

