name: Build and Push Docker Image

on:
  push:
  pull_request:
    branches:
      - master  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Install dependencies
        run: cargo build --release

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.event.pull_request.number }}
          enable_fibbot: "true"  # Set to "true" to enable Fibonacci calculation
          max_threshold: "100" # Set your desired max threshold
    

  comment:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job

    steps:
      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const body = `👋 Thanks for reporting! Here is the output from the Rust program:\n\n\`\`\`\n${{ steps.run_fibonacci.outputs.result }}\n\`\`\``;

            try {
              const response = await github.issues.createComment({
                issue_number: issueNumber,
                owner: owner,
                repo: repo,
                body: body
              });
              console.log('Response:', response);
            } catch (error) {
              console.error('Error:', error);
            }
