name: Build and Push Docker Image

on:
  push:
  pull_request:
    branches:
      - master  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use custorm action
        uses: ./
        with:
          enable_fibbot: "true"
          max_threshold: "100"
  comment:
    runs-on: ubuntu-latest
    steps:
        name: Comment on PR
        uses: actions/github-script@v3
        with:
        script: |
          const issueNumber = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const body = `👋 Thanks for reporting! Here is the output from the Rust program:\n\n\`\`\`\n${{ steps.run_rust.outputs.result }}\n\`\`\``;

          try {
            const response = await github.issues.createComment({
              issue_number: issueNumber,
              owner: owner,
              repo: repo,
              body: body
            });
            console.log('Response:', response);
          } catch (error) {
          }  console.error('Error: