name: "FibBot Action workflow"

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:


      - name: Install CA Certificates
        run: sudo apt-get update && sudo apt-get install -y ca-certificates
        
      - name: Test GitHub API Connectivity
        run: curl -I https://api.github.com
      - name: Cached Cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/.git/db/
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-go-
      
      - name: Debug Environment Variables
        run: |
          echo "PR_NUMBER: $PR_NUMBER"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          echo "GITHUB_OWNER: $GITHUB_OWNER"
           echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build, RUN AND COMMENT 
        id: fibbot
        uses: ./
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          INPUT_ENABLE_FIB: "true"
          INPUT_MAX_THRESHOLD: "100"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}