name: "FibBot Action workflow"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Comment PR 
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "Thank you for your pull request! A FibBot will review it shortly."

      - name: Build and run FibBot
        uses: ./
        with:
          pr_number: ${{ github.event.pull_request.number }}
          enable_fib: "true"
          max_threshold: "100"
          github_token: ${{ secrets.GITHUB_TOKEN }}