name: Build and Push Docker Image

on:
  push:
  pull_request:
    branches:
      - master  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use custom action
        uses: ./
        with:
          enable_fibbot: "true"
          max_threshold: "100"

   
  comment:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job

    steps:
      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const body = `👋 Thanks for reporting! Here is the output from the Rust program:\n\n\`\`\`\n${{ needs.build.outputs.result }}\n\`\`\``;

            try {
              const response = await github.issues.createComment({
                issue_number: issueNumber,
                owner: owner,
                repo: repo,
                body: body
              });
              console.log('Response:', response);
            } catch (error) {
              console.error('Error:', error);
            }
