name: Fibonacci Calculation and PR Comment

on:
    
    pull_request:
    types: [opened, synchronize]

    permissions: 
      pull-request: write
      content: re

jobs:
  calculate-fibonacci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use custom action
        uses: ./
        with:
          enable_fibbot: "true"
          max_threshold: "100"


          

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install jq (for parsing JSON)
        run: sudo apt-get install -y jq

      - name: Build and run Rust program
        id: fibonacci
        run: |
          # Build and run the Rust program, capturing the output
          FIBONACCI_RESULT=$(cargo run -q)
          echo "FIBONACCI_RESULT=$FIBONACCI_RESULT" >> $GITHUB_ENV

          # Extract PR number from the GitHub event payload
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV

      - name: Post comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const { FIBONACCI_RESULT, PR_NUMBER } = process.env;
            if (!PR_NUMBER) {
              console.error("PR_NUMBER is not set. Cannot post comment.");
              process.exit(1);
            }
            github.rest.issues.createComment({
              issue_number: PR_NUMBER,  // Use the PR_NUMBER environment variable
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Here is the Fibonacci sequence: ${FIBONACCI_RESULT || "No result"}`
            });
            