name: "FibBot Action workflow"

on:
  pull_request:
    types: [opened, synchronize, reopened]

    permissions:
      pull-requests: write
      contents: read

jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build , RUN AND COMMENT 
        id: fibbot
        uses: ./
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          INPUT_ENABLE_FIB: "true"
          INPUT_MAX_THRESHOLD: "100"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.actor.repository }}
          GITHUB_REPOSITORY: ${{ github.repository }}

     
     