name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use custorm action
        uses: ./
        with:
          enable_fibbot: "true"
          max_threshold: "100"

      
