name: Build and Push Docker Image

on:
  push:
  pull_request:
    branches:
      - master  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use custorm action
        uses: ./
        with:
          enable_fibbot: "true"
          max_threshold: "100"
  comment:
    runs-on: ubuntu-latest

    steps:
      -  name: Comment on PR
         uses: actions/github-script@v3
         with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.issue.number) {
              await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '👋 Thanks for reporting!'
              });
            } else {
              console.log('No issue number found. This may not be a pull request event.');
            }
